#!/bin/sh
set -e

# Register nvim as an alternative for vi and vim, view, editor
update-alternatives --install /usr/bin/vi vi /usr/bin/wovim 60
update-alternatives --install /usr/bin/vim vim /usr/bin/wovim 60
update-alternatives --install /usr/bin/view view /usr/bin/wovim 60

exit 0
